# -*- coding: utf-8 -*-
"""CAMP6_MACHINE_TEST.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16LWfDo4Nl9vrXg0A6ROk8feAZ5k90CvN

# AI-Based Fake News & Misinformation Detection System

## Objective
- Classify news articles as REAL or FAKE
- Highlight suspicious phrases
- Generate credibility explanation
- Provide confidence score
- Evaluate model performance using standard metrics

Dataset: Fake and Real News Dataset
"""

import pandas as pd
import numpy as np
import re
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

!pip install lime
from lime.lime_text import LimeTextExplainer

true_df = pd.read_csv("/content/drive/MyDrive/Camp6 Machine Test/True.csv")
fake_df = pd.read_csv("/content/drive/MyDrive/Camp6 Machine Test/Fake.csv")

true_df["label"] = 1   # REAL
fake_df["label"] = 0   # FAKE

df = pd.concat([true_df, fake_df])
df = df.sample(frac=1).reset_index(drop=True)

df.head()

def clean_text(text):
    text = text.lower()
    text = re.sub(r'http\S+', '', text)
    text = re.sub(r'[^a-zA-Z ]', '', text)
    return text

df["text"] = df["text"].apply(clean_text)

X_train, X_test, y_train, y_test = train_test_split(
    df["text"], df["label"], test_size=0.2, random_state=42
)

vectorizer = TfidfVectorizer(max_features=5000)

X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

model = LogisticRegression()
model.fit(X_train_vec, y_train)

pred = model.predict(X_test_vec)
print(classification_report(y_test, pred))

cm = confusion_matrix(y_test, pred)
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

def predict_news(text):
    cleaned = clean_text(text)
    vec = vectorizer.transform([cleaned])

    prediction = model.predict(vec)[0]
    confidence = model.predict_proba(vec).max()

    label = "REAL" if prediction == 1 else "FAKE"
    return label, confidence

explainer = LimeTextExplainer(class_names=["FAKE","REAL"])

def predict_proba(texts):
    vec = vectorizer.transform(texts)
    return model.predict_proba(vec)

sample_text = X_test.iloc[0]

exp = explainer.explain_instance(
    sample_text,
    predict_proba,
    num_features=10
)

exp.show_in_notebook()

important_words = [word for word, weight in exp.as_list()]

print("Suspicious / Important phrases:")
print(important_words)

def generate_explanation(pred, confidence):
    if pred == "FAKE":
        return f"The article is predicted as FAKE with {confidence:.2f} confidence because it contains language patterns commonly associated with misleading or unverified news."
    else:
        return f"The article is predicted as REAL with {confidence:.2f} confidence as the writing style and content resemble verified news sources."

label, confidence = predict_news(sample_text)

print("===================================")
print(" FAKE NEWS DETECTION RESULT ")
print("===================================")
print("Prediction :", label)
print("Confidence :", round(confidence*100,2), "%")
print("Explanation:", generate_explanation(label, confidence))
print("===================================")

user_input = input("Paste news article here:\n")

label, confidence = predict_news(user_input)

print("\n===================================")
print(" FAKE NEWS DETECTION RESULT ")
print("===================================")
print("Prediction :", label)
print("Confidence :", round(confidence*100,2), "%")
print("Explanation:", generate_explanation(label, confidence))
print("===================================")

